# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `selenium-devtools` gem.
# Please instead update this file by running `bin/tapioca gem selenium-devtools`.

# source://selenium-devtools//lib/selenium/devtools.rb#20
module Selenium; end

# source://selenium-devtools//lib/selenium/devtools.rb#21
module Selenium::DevTools
  class << self
    # source://selenium-devtools//lib/selenium/devtools.rb#25
    def load_version; end

    # Returns the value of attribute version.
    #
    # source://selenium-devtools//lib/selenium/devtools.rb#23
    def version; end

    # Sets the attribute version
    #
    # @param value the value to set the attribute version to.
    #
    # source://selenium-devtools//lib/selenium/devtools.rb#23
    def version=(_arg0); end

    private

    # source://selenium-devtools//lib/selenium/devtools.rb#47
    def load_old_version(version); end

    # Try to load up to 2 versions back
    #
    # source://selenium-devtools//lib/selenium/devtools.rb#36
    def load_older_version; end
  end
end
