# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DestroyDemoActivityJob`.
# Please instead update this file by running `bin/tapioca dsl DestroyDemoActivityJob`.

class DestroyDemoActivityJob
  class << self
    sig { params(activity: ::Activity).returns(T.any(DestroyDemoActivityJob, FalseClass)) }
    def perform_later(activity); end

    sig { params(activity: ::Activity).void }
    def perform_now(activity); end
  end
end
