# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DestroyDemoActivitiesJob`.
# Please instead update this file by running `bin/tapioca dsl DestroyDemoActivitiesJob`.

class DestroyDemoActivitiesJob
  class << self
    sig { returns(T.any(DestroyDemoActivitiesJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
