# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DestroyDemoActivitiesJob`.
# Please instead update this file by running `bin/tapioca dsl DestroyDemoActivitiesJob`.

class DestroyDemoActivitiesJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: DestroyDemoActivitiesJob).void)
      ).returns(T.any(DestroyDemoActivitiesJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
