# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ImportActivitiesJob`.
# Please instead update this file by running `bin/tapioca dsl ImportActivitiesJob`.

class ImportActivitiesJob
  class << self
    sig { params(options: T.untyped).returns(T.any(ImportActivitiesJob, FalseClass)) }
    def perform_later(**options); end

    sig { params(options: T.untyped).void }
    def perform_now(**options); end
  end
end
