# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ImportActivitiesJob`.
# Please instead update this file by running `bin/tapioca dsl ImportActivitiesJob`.

class ImportActivitiesJob
  class << self
    sig do
      params(
        options: T.untyped,
        block: T.nilable(T.proc.params(job: ImportActivitiesJob).void)
      ).returns(T.any(ImportActivitiesJob, FalseClass))
    end
    def perform_later(**options, &block); end

    sig { params(options: T.untyped).void }
    def perform_now(**options); end
  end
end
