# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ImportActivitiesForUserJob`.
# Please instead update this file by running `bin/tapioca dsl ImportActivitiesForUserJob`.

class ImportActivitiesForUserJob
  class << self
    sig do
      params(
        user: ::User,
        block: T.nilable(T.proc.params(job: ImportActivitiesForUserJob).void)
      ).returns(T.any(ImportActivitiesForUserJob, FalseClass))
    end
    def perform_later(user, &block); end

    sig { params(user: ::User).void }
    def perform_now(user); end
  end
end
