# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MobileSubscriptionMailer`.
# Please instead update this file by running `bin/tapioca dsl MobileSubscriptionMailer`.

class MobileSubscriptionMailer
  class << self
    sig { params(subscription: ::MobileSubscription).returns(::ActionMailer::MessageDelivery) }
    def created_email(subscription); end

    sig { returns(::ActionMailer::MessageDelivery) }
    def current_user; end
  end
end
