# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RegisterGoogleCalendarChannelForUserJob`.
# Please instead update this file by running `bin/tapioca dsl RegisterGoogleCalendarChannelForUserJob`.

class RegisterGoogleCalendarChannelForUserJob
  class << self
    sig do
      params(
        user: ::User,
        block: T.nilable(T.proc.params(job: RegisterGoogleCalendarChannelForUserJob).void)
      ).returns(T.any(RegisterGoogleCalendarChannelForUserJob, FalseClass))
    end
    def perform_later(user, &block); end

    sig { params(user: ::User).void }
    def perform_now(user); end
  end
end
