# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ScheduleActivityMobileNotificationsJob`.
# Please instead update this file by running `bin/tapioca dsl ScheduleActivityMobileNotificationsJob`.

class ScheduleActivityMobileNotificationsJob
  class << self
    sig do
      params(
        activity: ::Activity,
        block: T.nilable(T.proc.params(job: ScheduleActivityMobileNotificationsJob).void)
      ).returns(T.any(ScheduleActivityMobileNotificationsJob, FalseClass))
    end
    def perform_later(activity, &block); end

    sig { params(activity: ::Activity).void }
    def perform_now(activity); end
  end
end
