# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SendScheduledMobileNotificationTextsJob`.
# Please instead update this file by running `bin/tapioca dsl SendScheduledMobileNotificationTextsJob`.

class SendScheduledMobileNotificationTextsJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: SendScheduledMobileNotificationTextsJob).void)
      ).returns(T.any(SendScheduledMobileNotificationTextsJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
