# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SendScheduledMobileNotificationTextsJob`.
# Please instead update this file by running `bin/tapioca dsl SendScheduledMobileNotificationTextsJob`.

class SendScheduledMobileNotificationTextsJob
  class << self
    sig { returns(T.any(SendScheduledMobileNotificationTextsJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
