# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SendMobileSubscriberTextJob`.
# Please instead update this file by running `bin/tapioca dsl SendMobileSubscriberTextJob`.

class SendMobileSubscriberTextJob
  class << self
    sig do
      params(
        subscriber: ::MobileSubscriber,
        message: ::String,
        block: T.nilable(T.proc.params(job: SendMobileSubscriberTextJob).void)
      ).returns(T.any(SendMobileSubscriberTextJob, FalseClass))
    end
    def perform_later(subscriber, message, &block); end

    sig { params(subscriber: ::MobileSubscriber, message: ::String).void }
    def perform_now(subscriber, message); end
  end
end
