# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SyncGoogleCalendarChannelsJob`.
# Please instead update this file by running `bin/tapioca dsl SyncGoogleCalendarChannelsJob`.

class SyncGoogleCalendarChannelsJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: SyncGoogleCalendarChannelsJob).void)
      ).returns(T.any(SyncGoogleCalendarChannelsJob, FalseClass))
    end
    def perform_later(&block); end

    sig { void }
    def perform_now; end
  end
end
