# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SyncGoogleCalendarChannelsJob`.
# Please instead update this file by running `bin/tapioca dsl SyncGoogleCalendarChannelsJob`.

class SyncGoogleCalendarChannelsJob
  class << self
    sig { returns(T.any(SyncGoogleCalendarChannelsJob, FalseClass)) }
    def perform_later; end

    sig { void }
    def perform_now; end
  end
end
